local pywal = require('pywal')
pywal.setup()
require("core.plugin_config.cmp")
require("core.plugin_config.dashboard")
require("core.plugin_config.indent-blankline")
require("core.plugin_config.lualine")
require("core.plugin_config.neoterm")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.telescope")
require("core.plugin_config.treesitter")
